from oman_compliance.oman_compliance.constants import VAT_CATEGORY_SELECT_OPTIONS

MODULE = "Oman Compliance"

CUSTOM_FIELDS = {
	"Company": [
		{
			"fieldname": "company_name_in_arabic",
			"label": "Company Name in Arabic",
			"fieldtype": "Data",
			"insert_after": "company_name",
			"translatable": 0,
			"module": MODULE,
		},
	],
	("Company", "Customer", "Supplier"): [
		{
			"fieldname": "oman_trn",
			"label": "TRN",
			"fieldtype": "Data",
			"insert_after": "tax_id",
			"translatable": 0,
			"module": MODULE,
		},
	],
	"Customer": [
		{
			"fieldname": "customer_name_in_arabic",
			"label": "Customer Name in Arabic",
			"fieldtype": "Data",
			"insert_after": "customer_name",
			"translatable": 0,
			"module": MODULE,
		},
	],
	"Supplier": [
		{
			"fieldname": "supplier_name_in_arabic",
			"label": "Supplier Name in Arabic",
			"fieldtype": "Data",
			"insert_after": "supplier_name",
			"translatable": 0,
			"module": MODULE,
		},
	],
	"Address": [
		{
			"fieldname": "address_in_arabic",
			"label": "Address in Arabic",
			"fieldtype": "Small Text",
			"insert_after": "address_line2",
			"translatable": 0,
			"module": MODULE,
		},
		{
			"fieldname": "designated_zone",
			"label": "Designated Zone",
			"fieldtype": "Link",
			"options": "Designated Zone",
			"insert_after": "country",
			"translatable": 0,
			"module": MODULE,
		},
	],
	(
		"Sales Order Item",
		"Quotation Item",
		"Delivery Note Item",
		"Sales Invoice Item",
		"Purchase Invoice Item",
	): [
		{
			"fieldname": "vat_category",
			"label": "VAT Category",
			"fieldtype": "Select",
			"options": VAT_CATEGORY_SELECT_OPTIONS,
			"insert_after": "item_tax_template",
			"in_list_view": 1,
			"translatable": 0,
			"module": MODULE,
		},
	],
	"Item Tax Template": [
		{
			"fieldname": "vat_category",
			"label": "VAT Category",
			"fieldtype": "Select",
			"options": VAT_CATEGORY_SELECT_OPTIONS,
			"insert_after": "disabled",
			"translatable": 0,
			"module": MODULE,
		},
		{
			"fieldname": "fetch_vat_accounts",
			"label": "Fetch VAT Accounts",
			"fieldtype": "Button",
			"insert_after": "section_break_5",
			"module": MODULE,
		},
	],
	"Purchase Invoice": [
		{
			"fieldname": "oman_vat_section",
			"label": "Oman VAT",
			"fieldtype": "Section Break",
			"insert_after": "tax_category",
			"module": MODULE,
		},
		{
			"fieldname": "is_reverse_charge",
			"label": "Reverse Charge Applicable",
			"fieldtype": "Check",
			"insert_after": "oman_vat_section",
			"translatable": 0,
			"module": MODULE,
		},
		{
			"fieldname": "is_gcc_supplier",
			"label": "GCC Supplier",
			"fieldtype": "Check",
			"insert_after": "is_reverse_charge",
			"read_only": 1,
			"translatable": 0,
			"module": MODULE,
		},
		{
			"fieldname": "column_break_oman_pinv",
			"fieldtype": "Column Break",
			"insert_after": "is_gcc_supplier",
			"module": MODULE,
		},
		{
			"fieldname": "is_import_of_goods",
			"label": "Import of Goods",
			"fieldtype": "Check",
			"insert_after": "column_break_oman_pinv",
			"read_only": 1,
			"translatable": 0,
			"module": MODULE,
		},
		{
			"fieldname": "is_postponed_import_vat",
			"label": "Postponed Import VAT",
			"fieldtype": "Check",
			"insert_after": "is_import_of_goods",
			"translatable": 0,
			"module": MODULE,
		},
	],
	"Sales Invoice": [
		{
			"fieldname": "is_export",
			"label": "Export",
			"fieldtype": "Check",
			"insert_after": "customer_address",
			"read_only": 1,
			"translatable": 0,
			"module": MODULE,
		},
		{
			"fieldname": "is_simplified_tax_invoice",
			"label": "Simplified Tax Invoice",
			"fieldtype": "Check",
			"insert_after": "is_export",
			"read_only": 1,
			"translatable": 0,
			"module": MODULE,
		},
	],
}
